[package]
name = "vlsvrs"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.22.0"
ndarray = "0.16.1"
num-traits = "0.2.19"
raylib = "5.5.1"
regex = "1.11.1"
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.6"

[[bin]]
name="test"
path="src/main.rs"

[[bin]]
name="vlsvdump"
path="src/vlsvdump.rs"
